'use client'
import { useRouter } from 'next/navigation'
import { Sparkles } from '@/components/MagicUI'

export default function TermsPage() {
  const router = useRouter()

  return (
    <main className="min-h-screen bg-magic-gradient p-6">
      <Sparkles count={8} />

      <div className="max-w-3xl mx-auto relative z-10">
        <button
          onClick={() => router.back()}
          className="text-purple-300 hover:text-white mb-6"
        >
          ← Back
        </button>

        <div className="bg-white/10 backdrop-blur-md rounded-2xl border border-white/10 p-8">
          <h1 className="text-white text-3xl font-display mb-6">Terms of Service</h1>
          <p className="text-purple-300 text-sm mb-8">Last updated: January 2026</p>

          <div className="prose prose-invert prose-purple max-w-none space-y-6 text-purple-100">
            
            <section>
              <h2 className="text-white text-xl font-display mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using My Story Magic ("the Service"), you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">2. Description of Service</h2>
              <p>
                My Story Magic is an AI-powered bedtime story generation service that creates personalised stories 
                for children and offers voice cloning technology to narrate stories in family members' voices.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">3. User Accounts</h2>
              <p>
                You must be at least 18 years old to create an account. You are responsible for maintaining 
                the confidentiality of your account credentials and for all activities under your account.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">4. Prohibited Conduct</h2>
              <p><strong>You expressly warrant and agree that you will NOT:</strong></p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li><strong>Use the Service for any criminal activity</strong> or in connection with any unlawful purpose whatsoever</li>
                <li><strong>Use the Service to cause harm</strong> to any person, including but not limited to harassment, stalking, threats, defamation, or psychological harm</li>
                <li><strong>Generate content that is harmful, abusive, violent, sexual, or inappropriate</strong> for children or any audience</li>
                <li>Use the Service to facilitate fraud, deception, or misrepresentation of any kind</li>
                <li>Attempt to circumvent usage limits, security measures, or content filters</li>
                <li>Share account access with unauthorised users</li>
                <li>Use the Service in any manner that could damage, disable, or impair the Service</li>
              </ul>
              <p className="mt-3 font-semibold text-yellow-300">
                Violation of these prohibitions may result in immediate account termination and may be reported to relevant authorities.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">5. Intellectual Property & Copyright</h2>
              <p><strong>You expressly warrant and agree that:</strong></p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You will <strong>NOT request or generate content</strong> based on copyrighted characters, franchises, trademarks, or intellectual property owned by third parties</li>
                <li>You will <strong>NOT infringe upon any copyright, trademark, patent</strong>, or other proprietary rights of any party</li>
                <li>You understand that requesting protected IP content (such as characters from movies, books, TV shows, or games) is a violation of these terms</li>
                <li>If you become aware of any inadvertent breach of intellectual property rights, you will <strong>immediately cease use of the infringing content</strong> and notify us</li>
                <li>You agree to <strong>promptly remedy any breach</strong> of intellectual property rights at your own expense</li>
              </ul>
              <p className="mt-3">
                Stories generated by the Service are created using AI and are provided for personal, 
                non-commercial use only. We do not claim ownership of generated stories but reserve 
                the right to use anonymised data to improve our services.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">6. Parental Responsibility & Content Review</h2>
              <p><strong>As the parent or guardian using this Service, you expressly warrant and agree that:</strong></p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You are <strong>solely responsible</strong> for reviewing all generated story content <strong>BEFORE</strong> playing it to any child</li>
                <li>You will <strong>verify that each story is appropriate</strong> for your child's age, maturity, and sensitivities before playback</li>
                <li>You understand that AI-generated content may occasionally produce unexpected results despite our content filters</li>
                <li>You <strong>warrant that any story you play to a child has been reviewed by you</strong> and deemed appropriate</li>
                <li>You accept full responsibility for any content played to children under your supervision</li>
                <li>You will immediately report any inappropriate content generated by the Service</li>
              </ul>
              <p className="mt-3 font-semibold text-yellow-300">
                We implement content safety filters, but no automated system is perfect. Parental review is essential.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">7. Voice Cloning - Consent & Permissions</h2>
              <p><strong>By using our voice cloning feature, you expressly warrant and agree that:</strong></p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You have <strong>obtained explicit, informed consent</strong> from the person whose voice is being cloned</li>
                <li>You have the <strong>legal right and authority</strong> to record and clone that person's voice</li>
                <li>The voice clone will <strong>ONLY be used for personal family storytelling</strong> within this Service</li>
                <li>You will <strong>NOT use cloned voices</strong> for impersonation, fraud, deception, commercial purposes, or any purpose outside this Service</li>
                <li>You will <strong>NOT clone the voice</strong> of any person without their knowledge and consent</li>
                <li>You will <strong>NOT clone the voice</strong> of any public figure, celebrity, or person whose voice rights you do not own</li>
                <li>You accept <strong>full liability</strong> for any misuse of voice cloning technology</li>
              </ul>
              <p className="mt-3 font-semibold text-yellow-300">
                Misuse of voice cloning technology may constitute fraud or identity theft under Australian law.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">8. Indemnification</h2>
              <p>
                You agree to <strong>indemnify, defend, and hold harmless</strong> My Story Magic, its operators, 
                affiliates, and their respective officers, directors, employees, and agents from and against 
                any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable 
                legal fees) arising out of or related to:
              </p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any rights of any third party</li>
                <li>Any content you generate, request, or distribute using the Service</li>
                <li>Your misuse of voice cloning technology</li>
                <li>Any claim that content you created infringes intellectual property rights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">9. Subscription and Billing</h2>
              <p>
                Paid subscriptions are billed monthly through the App Store (Apple) or Google Play. 
                Subscription management, including cancellation, is handled through your app store account. 
                Refunds are subject to the respective app store's refund policy.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">10. Service Availability</h2>
              <p>
                We strive to maintain Service availability but do not guarantee uninterrupted access. 
                We may modify, suspend, or discontinue features with reasonable notice. We are not 
                liable for any loss resulting from Service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">11. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by Australian law, the Service is provided "as is" 
                without warranties of any kind, either express or implied. We are not liable for any 
                indirect, incidental, special, consequential, or punitive damages arising from your 
                use of the Service, including but not limited to damages for loss of profits, goodwill, 
                data, or other intangible losses.
              </p>
              <p className="mt-2">
                Our total liability to you for any claims arising from or related to the Service shall 
                not exceed the amount you have paid us in the twelve (12) months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">12. Children's Safety</h2>
              <p>
                The Service is designed for parents and guardians to create content for children. 
                Children must not create accounts or use the Service without adult supervision. 
                We implement content filters to help ensure generated stories are age-appropriate, 
                but parental review remains essential.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">13. Termination</h2>
              <p>
                We reserve the right to immediately suspend or terminate accounts that violate these terms, 
                without prior notice or liability. You may delete your account at any time through the 
                Settings page, which will remove all your data from our systems.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">14. Governing Law & Jurisdiction</h2>
              <p>
                These terms are governed by and construed in accordance with the laws of Australia. 
                You irrevocably submit to the exclusive jurisdiction of the courts of Australia for 
                any disputes arising out of or relating to these terms or your use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">15. Severability</h2>
              <p>
                If any provision of these Terms is found to be unenforceable or invalid, that provision 
                shall be limited or eliminated to the minimum extent necessary so that these Terms shall 
                otherwise remain in full force and effect.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">16. Changes to Terms</h2>
              <p>
                We may update these terms from time to time. Continued use of the Service after 
                changes constitutes acceptance of the new terms. We will notify users of significant 
                changes via email or in-app notification.
              </p>
            </section>

            <section>
              <h2 className="text-white text-xl font-display mb-3">17. Contact</h2>
              <p>
                For questions about these Terms of Service, please contact us through the app.
              </p>
              <p className="mt-4 text-purple-300 text-sm">
                Australia
              </p>
            </section>

          </div>
        </div>
      </div>
    </main>
  )
}
